/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dipst.application.sturts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 12-24-2013
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class LoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** uname property */
	private String uname;

	/** confirmpassword property */
	private String confirmpassword;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.uname = uname;
		this.password = password;
		this.confirmpassword = confirmpassword;
	}

	/**
	 * Returns the uname.
	 * 
	 * @return String
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * Set the uname.
	 * 
	 * @param uname
	 *            The uname to set
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * Returns the confirmpassword.
	 * 
	 * @return String
	 */
	public String getConfirmpassword() {
		return confirmpassword;
	}

	/**
	 * Set the confirmpassword.
	 * 
	 * @param confirmpassword
	 *            The confirmpassword to set
	 */
	public void setConfirmpassword(String confirmpassword) {
		this.confirmpassword = confirmpassword;
	}

	/**
	 * Returns the password.
	 * 
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}